on:
  webhook:
    method: post

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Show raw payload
        run: |
          echo '--- RAW BODY START ---'
          echo '${{ toJson(on.webhook.outputs.body) }}'
          echo '--- RAW BODY END ---'

      - name: Post to Slack with Node
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          RAW_BODY: ${{ toJson(on.webhook.outputs.body) }}
        run: |
          node -e "
          const url = process.env.SLACK_WEBHOOK_URL;
          if (!url) { console.error('Missing secret SLACK_WEBHOOK_URL'); process.exit(1); }
          const raw = process.env.RAW_BODY || '[]';
          let data;
          try { data = JSON.parse(raw); } catch { console.error('Invalid JSON'); process.exit(1); }
          const arr = Array.isArray(data) ? data : [data];
          const https = require('https');
          const { URL } = require('url');
          const u = new URL(url);

          function post(text) {
            const body = JSON.stringify({ text });
            const opts = {
              protocol: u.protocol,
              hostname: u.hostname,
              port: u.port || 443,
              path: u.pathname + u.search,
              method: 'POST',
              headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }
            };
            const req = https.request(opts, res => {
              let out = '';
              res.on('data', c => out += c);
              res.on('end', () => {
                console.log('Slack status:', res.statusCode);
                console.log('Slack response:', out);
                if (res.statusCode < 200 || res.statusCode >= 300) process.exit(1);
              });
            });
            req.on('error', e => { console.error(e); process.exit(1); });
            req.write(body);
            req.end();
          }

          for (const it of arr) {
            const name = it.name || \`\${it.firstName || ''} \${it.lastName || ''}\`.trim();
            const email = it.emailAddress || '';
            const phone = it.phoneNumber || '';
            const id = it.id || '';
            const text = \`New lead created: \${name}\nEmail: \${email}\nPhone: \${phone}\nEspoCRM ID: \${id}\`;
            post(text);
          }
          "
