name: Actionsflow
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actionsflow/actionsflow-action@v1
        with:
          args: build
          json-secrets: ${{ toJson(secrets) }}
          json-github: ${{ toJson(github) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
